### ISSUE TITLE
Build failing - Signing for "hopepoint" requires a development team

### ISSUE THREAD

**Issue by jamieL10092** [9magnets/HopePoint#2]
After running HopePoint i receiving:

Signing for "hopepoint" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

Any ways around this? 

Thanks in advance

**Comment by geoffreyspencer** [comment]
You can build any app for iOS or tvOS without signing but you will not be able to install the apps on those devices unless you create a signing certificate and then a provisioning profile with that signed certificate. It is easy to do in Xcode. Use a search engine for more info on this.

**Comment by jamieL10092** [comment]
Sorry i should have been clearer, i'm trying to run the already built programme onto my iOS and started for the first time about an hour ago. Will i still need to create a signing certificate?

**Comment by jamieL10092** [comment]
i have now created a developer account how do i add that to xcode?

**Comment by CameronBanga** [comment]
@jamieL10092 See this guide, hopefully it can help you get through the problem: 

https://www.pdf-archive.com/2016/12/15/hopepoint-final/

If that doesn't help, Apple has extensive documentation here: 

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/LaunchingYourApponDevices/LaunchingYourApponDevices.html#//apple_ref/doc/uid/TP40012582-CH27-SW4

Hope you enjoy the app!
