### ISSUE TITLE
ios 9 err

### ISSUE THREAD

**Issue by zhibolau** [9magnets/HopePoint#3]
HI,

do i have to be on ios 10?

got err when using ios9: Signing for "hopepoint" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

thanks

**Comment by CameronBanga** [comment]
@zhibolau 

iOS 10 not required, see these guides, they should offer help:

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/LaunchingYourApponDevices/LaunchingYourApponDevices.html#//apple_ref/doc/uid/TP40012582-CH27-SW4

https://www.pdf-archive.com/2016/12/15/hopepoint-final/
